services:
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - rflandscaperpro

networks:
  rflandscaperpro:
    external: true
