services:
  frontend:
    build:
      dockerfile: frontend/Dockerfile.dev
    working_dir: /app/frontend
    volumes:
      - .:/app/frontend
      - ../shared:/app/shared
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
