services:
  frontend:
    build:
      dockerfile: frontend/Dockerfile.dev
    volumes:
      - .:/app
      - ../shared:/shared
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
