services:
  frontend:
    container_name: frontend
    image: rflandscaperpro/frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - rflandscaperpro

networks:
  rflandscaperpro:
    external: true
