services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env.development
    environment:
      NODE_ENV: development
      DB_HOST: db
      MAILHOG_HOST: mailhog
      MAILHOG_PORT: 1025
      REMOTE_LOG_HOST: logserver
      REMOTE_LOG_PORT: 9880
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: development
    depends_on:
      - backend
