services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env.development
    environment:
      NODE_ENV: development
      DB_HOST: db
      MAILHOG_HOST: mailhog
      MAILHOG_PORT: 1025
      REMOTE_LOG_HOST: logserver
      REMOTE_LOG_PORT: 9880
    depends_on:
      - db
      - logserver
  db:
    image: postgres:14
    container_name: rflandscaperpro_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rflandscaperpro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: development
    depends_on:
      - backend
  prometheus:
    image: prom/prometheus
    container_name: rflandscaperpro_prometheus
    volumes:
      - ./backend/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: rflandscaperpro_grafana
    depends_on:
      - prometheus
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./backend/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
  mailhog:
    image: mailhog/mailhog
    container_name: rflandscaperpro_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  logserver:
    image: fluent/fluentd:v1.16-debian
    container_name: rflandscaperpro_logserver
    volumes:
      - ./backend/fluentd.conf:/fluentd/etc/fluent.conf:ro
    env_file:
      - ./backend/env.example
    ports:
      - "${REMOTE_LOG_PORT:-9880}:${REMOTE_LOG_PORT:-9880}"

volumes:
  grafana_data:
  postgres_data:
