services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
