services:
  backend:
    image: rflandscaperpro/backend
    container_name: rflandscaperpro_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mailhog:
    image: mailhog/mailhog
    container_name: rflandscaperpro_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
