services:
  backend:
    build:
      dockerfile: backend/Dockerfile.dev
    volumes:
      - .:/app
      - ../shared:/shared
      - /app/node_modules
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
