services:
  backend:
    build:
      dockerfile: backend/Dockerfile.dev
    working_dir: /app/backend
    volumes:
      - .:/app/backend
      - ../shared:/app/shared
    env_file:
      - .env.development
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - DB_HOST=db
