services:
  backend:
    container_name: backend
    image: rflandscaperpro/backend
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - rflandscaperpro

networks:
  rflandscaperpro:
    driver: bridge
