global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    metrics_path: /metrics
    fallback_scrape_protocol: PrometheusText0.0.4
    static_configs:
      - targets: ['backend:3000']
