services:
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml:ro
    ports:
      - "3001:3000"
    networks:
      - rflandscaperpro

volumes:
  grafana_data:

networks:
  rflandscaperpro:
    external: true
